[package]
name = "dropbox"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3"
tokio = { version = "1.16", features = ["full"] }
futures-util = { version = "0.3", default-features = false, features = ["sink"] }
tokio-util = { version = "0.4", features = ["io"] }