version: "3.9"

services:
  node:
    image: node:19-alpine
    working_dir: /app
    volumes:
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
      - ./node_modules:/app/node_modules
      - ./index.js:/app/index.js
      - ./data/:/data
    command: ['yarn', 'dev']

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data:/data/
    ports:
      - 80:80
    