version: "3.9"

services:
  app:
    build:
      context: .
      target: builder
    image: tikhoplav/dropbox:builder
    working_dir: /app
    volumes:
      - .:/app
      - ./cache:/usr/local/cargo/registry
      - ./data/:/data
    ports:
      - 80:80
    # command: ['cargo-watch', '-c', '-w', './src', '-x', 'run']
    command: ['cargo', 'run']

  # nginx:
  #   image: nginx:alpine
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - ./data:/data/
  #   ports:
  #     - 80:80
    